<?php
$this->headTitle('Moon');

$this->mainMenu()->setActiveItemId('vposmoon');

$form->get('scan')->setAttributes([
	'class' => 'form-control',
	'rows' => '20',
	'id' => 'scanarea',
	'placeholder' => 'paste your scan from SCAN, DSCAN or survey scan HERE',
	'required' => true
]);

$current_route = $this->currentRoute()->getRoute();

//ini_set('xdebug.var_display_max_depth', 3); var_dump($moon_list);
//ini_set('xdebug.var_display_max_depth', 3); var_dump($filters);

if (empty($filters['info_system']['constellation'])) {
	$location_string = $filters['info_system']['itemname'] . ' (Constellation in ' . $filters['info_system']['region'] . ')';
} else {
	$location_string = $filters['info_system']['itemname'] . ' (' . $filters['info_system']['region'] . ')';
}
?>
<script>
	var sl_messages = <?= json_encode($message); ?>;
	var filters_json = <?= json_encode($filters_json); ?>;
	var current_route = <?= json_encode($current_route); ?>;
</script>	
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
	<div class="col-md-9 col-sm-10">
		<div class="row">
			<div class="col-md-6">
				<!-- start system name -->
				<div class="form-group form-group-lg addpaddingtop20">
					<select class="form-control select2-typeahead-system" name="selectsystem" id="selectsystem">
						<option value="<?= $this->escapeHtml($filters['info_system']['itemid']); ?>" selected><?= $this->escapeHtml($location_string); ?></option>
					</select>
				</div>
				<div>
					<?= $this->vpViewTool()->createNeighboursNavigation($filters['info_system']); ?>
				</div>
			</div>
			<!-- start filter area -->
			<div class="col-md-2">
				<div class="form-group form-group-sm checkbox">
					<input type="checkbox" id="filter_gooonly" <?= (!empty($filters['filter_gooonly']) && $filters['filter_gooonly'] == "1" ? 'checked' : '' ) ?>>
					<label for="filter_gooonly">show all moons</label>
				</div>
			</div>
			<div class="col-md-4">
				<!-- facette filter Composition -->
				<div class="form-group form-group-sm checkbox">
					<input type="checkbox" id="detail_filter_composition" <?= (!empty($filters['detail_filter_composition']) && $filters['detail_filter_composition'] == "1" ? 'checked' : '' ) ?>>
					<label for="detail_filter_composition">
						Composition - Filter <?= (!empty($filters['composition']) ? '&nbsp; <a href="/" class="resetswitch" data-id="selectcomposition">reset</a>' : ''); ?></label>
					<select class="form-control" name="selectcomposition" id="selectcomposition">
						<option value="0">please select to filter by Composition</option>
						<?= $this->vpViewTool()->getCompositionListAsOptions($filters['info_system']['id'], (!empty($filters['composition']) ? $filters['composition'] : 0)); ?>
					</select>
				</div>
				<!-- facette filter Ore -->
				<div class="form-group form-group-sm checkbox">
					<input type="checkbox" id="detail_filter_ore" <?= (!empty($filters['detail_filter_ore']) && $filters['detail_filter_ore'] == "1" ? 'checked' : '' ) ?>>
					<label for="detail_filter_ore">Ore - Filter <?= (!empty($filters['ore']) ? '&nbsp; <a href="/" class="resetswitch" data-id="selectore">reset</a>' : ''); ?></label>
					<select class="form-control" name="selectore" id="selectore">
						<option value="0">please select to filter by Ore</option>
						<?= $this->vpViewTool()->getOreListAsOptions($filters['info_system']['id'], (!empty($filters['ore']) ? $filters['ore'] : 0)); ?>
					</select>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<table id="moontable" class="table table-hover table-striped table-responsive" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th data-priority="1">Planet / Moon</th>
							<?php if (!empty($filters['detail_filter_composition']) && $filters['detail_filter_composition'] == "1"): ?>
								<th data-priority="3">Composition<div class="sub">(<span class="gooval">amount</span> / <span class="gooname">name</span> / <span class="gooprice">ISK</span>)</div></th>
							<?php endif; ?>
							<th data-priority="2">Value</th>
							<?php if (!empty($filters['detail_filter_ore']) && $filters['detail_filter_ore'] == "1"): ?>
								<th data-priority="3">Ore<div class="sub">(<span class="gooval">amount</span> / <span class="gooname">name</span> / <span class="gooprice">ISK</span>)</div></th>
							<?php endif; ?>
							<th data-priority="2">Ore-Value</th>
							<th>Structure</th>
							<th>Owner</th>
							<th>Scanned</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($moon_list as $key => $moon): ?>
							<tr>
								<td>
									<a href="<?= $this->vpViewTool()->createExternalSystemURL($moon['map_name']); ?>" class="unobtrusive" target="_blank"><?= $this->escapeHtml($moon['moonname']) ?>
									[<?= $this->vpViewTool()->convertMoonToShortform($moon['moonname']); ?>]</a></td>
									<?php if (!empty($filters['detail_filter_composition']) && $filters['detail_filter_composition'] == "1"): ?>
								<td><?= $this->vpViewTool()->renderMoonComposition($moon['goo']); ?></td>
								<?php endif; ?>
								<td>
								<?php if($moon['atmoonid']): ?>
									<?= $this->vpViewTool()->calculateMoonComposition($moon['goo']); ?>
								<?php endif; ?>
								</td>
								<?php if (!empty($filters['detail_filter_ore']) && $filters['detail_filter_ore'] == "1"): ?>
									<td><?= $this->vpViewTool()->renderMoonMateriallist($moon['materiallist']); ?></td>
								<?php endif; ?>
								<td>
								<?php if($moon['atmoonid']): ?>
									<?= number_format(round(intval($this->vpViewTool()->renderMoonMaterialValue($moon['materiallist'])) / 1000), 0); ?> k
								<?php endif; ?>
								</td>
								<td>
									<a href="#" class="structlink" data-toggle="modal" data-structid="<?= $moon['structid']; ?>" data-structtype="<?= $moon['structtype']; ?>" data-structgivename="<?= $moon['structgivename']; ?>" data-scorpid="<?= $moon['structcorpid']; ?>" data-scorpname="<?= $moon['structcorpname']; ?>"  data-scorpticker="<?= $moon['structcorpticker']; ?>" data-moonid="<?= $moon['moonid']; ?>" data-target="#structureEditModal">
										<?= ($moon['structname'] ? $moon['structname'] : '<i class="glyphicon glyphicon-plus passive"></i>'); ?></a><br /><span class="secondarytext"><?= $moon['structgivename']; ?></span>
								</td>
								<td>
									<a href="#" class="structlink" data-toggle="modal" data-structid="<?= $moon['structid']; ?>" data-structtype="<?= $moon['structtype']; ?>" data-structgivename="<?= $moon['structgivename']; ?>" data-scorpid="<?= $moon['structcorpid']; ?>" data-scorpname="<?= $moon['structcorpname']; ?>"  data-scorpticker="<?= $moon['structcorpticker']; ?>" data-moonid="<?= $moon['moonid']; ?>" data-target="#structureEditModal">
										<?= ($moon['structcorpticker'] ? $this->escapeHtml($moon['structcorpticker']) : '<i class="glyphicon glyphicon-plus passive"></i>'); ?></a>
								</td>
								<td>
								<?php if($moon['atmoonid']): ?>									
									<?= date_format($moon[0]->getLastseenDate(), 'Y-m-d H:i:s'); ?><br />
										<span class="secondarytext"><?= $moon['uchgddat']; ?></span>
								<?php else: ?>
									not scanned
								<?php endif; ?>
									<span  class="tdview">
										<?php if($moon['atmoonid']): ?>
										<a class="btn btn-xs btn-danger"  data-toggle="modal" data-target="#nopeModal"
										   href="<?= $this->url('vposmoon', ['action' => 'delete', 'id' => $moon[0]->getMoonId()]); ?>" 
										   title="delete Moon"><span class="glyphicon glyphicon-remove"></span></a>
										<?php endif; ?>
									</span>									
								</td>
							</tr>
						<?php endforeach; ?>						
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- start scan area -->
	<div class="col-md-3 col-sm-2">
		<div class="row">
			<button type="button" class="btn btn-info btn-sm pull-right" data-toggle="modal" data-target="#helpModal">
				<span class="glyphicon glyphicons-question-sign"></span> Help
			</button>
			<?php if ($this->access('moon.manage')): ?>
				<a href="<?= $this->url('vposmoon', ['action' => 'dlMoonsCsv']); ?>" class="btn btn-success btn-sm pull-right" title="download Moon data as CSV">
					<span class="glyphicon glyphicons-question-sign"></span> DL-CSV
				</a>
			<?php endif; ?>
		</div>
		<div class="row">
			<form class="form-signin" method="post">
				<?= $this->formLabel($form->get('scan')); ?>
				<?= $this->formElement($form->get('scan')); ?>
				<?= $this->formElementErrors($form->get('scan')); ?>
				<button class="btn btn-sm btn-primary btn-block" type="submit">submit your scan</button>
			</form>
		</div>
	</div>
</div>

<!-- Structure Edit Modal -->
<div class="modal fade" id="structureEditModal"  style="overflow:hidden;" role="dialog" aria-labelledby="structeditLabel">
    <div class="modal-dialog">
		<div class="modal-content">
			<form id="structureEditForm" role="form" action="/vposmoon/editStructureJson/0" method="POST">
				<!-- Modal Header -->
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">&times;</span>
						<span class="sr-only">Close</span>
					</button>
					<h4 class="modal-title" id="myModalLabel">Edit Structure</h4>
				</div>

				<!-- Modal Body -->
				<div class="modal-body">
					<input type="hidden" name="moonid" id="structureEditFormMoonId" value="0">
					<input type="hidden" name="structureid" id="structureEditFormStructureId" value="0">
					<div class="form-group">
						<label for="structedittype">Type of Structure</label>
						<select class="form-control" name="struct_item_id" id="structedittype">
							<option value="0">please select a structure</option>
							<?= $this->vpViewTool()->getEveTypesListAsOptions([1406]); ?>
						</select>						
					</div>
					<div class="form-group">
						<label for="structeditcorp">Owning Corporation</label>
						<select class="form-control" name="owning_corp" id="structeditcorp"></select>
					</div>
					<div class="form-group">
						<label for="structeditname">Name of Structure</label>
						<input type="text" name="struct_name" class="form-control" id="structeditname" placeholder="placeholder"/>
					</div>
				</div>

				<!-- Modal Footer -->
				<div class="modal-footer">
					<button type="button" class="btn btn-link pull-left" id="structureDeleteFormSubmit">delete structure</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-primary" value="Save changes" id="structureEditFormSubmit">
				</div>
			</form>
		</div>
    </div>
</div>



<!-- Help Modal -->
<div class="modal fade" id="helpModal" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Scan What?</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-6">
						<img src="img/eve_moon_probe_window.jpg" alt=""/>
					</div>
					<div class="col-md-6">
						<p>
							The &laquo;Moon Probe and Analysis&raquo; window offer a button &laquo;in the right bottom&raquo;. After you pressed this
							button navigate to <span class="syklizer">Syklizer - Moon</span> and paste the result into the big area to the right. 
						</p>
						<p>Then press the button &laquo;submit your scan&raquo; below the area and hold a sec. The table to the left will get updated soon and show your
							scan results.
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Nope Modal -->
<div class="modal fade" id="nopeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Nope?!</h4>
			</div>
			<div class="modal-body">
				Sorry folks, this function is not supported yet.
			</div>
		</div>
	</div>
</div>