<?php if (!empty($struct_list)): ?>
    <?php foreach ($struct_list as $key => $struct): ?>
    <div class="row card-row">
        <div class="col-sm-2 text-right">
            <img src="https://images.evetech.net/types/<?=$struct['at_typeId'];?>/render?size=32" title="<?=$this->escapeHtml($struct['it_typename']);?>">
        </div>
        <div class="col-sm-6">
            <span class="">
                <?=$this->escapeHtml($struct['at_structureName']);?></span>
                (<?=$this->escapeHtml($struct['own_corpticker']);?>)<br/>
                <span class="secondarytext"><?=($struct['celest_name'] ? $struct['celest_name'] : $struct['map_name'])?></span>
                
        </div>
        <div class="col-sm-4 text-center">
            <span class="tertiary"><?=$struct['at_structureState']?></span><br/>
            <?=$this->vpViewTool()->formatReinforceDate($struct['at_reinforceWeekday'], $struct['at_reinforceHour']);?>
        </div>
    </div>
    <?php endforeach;?>
<?php else: ?>
    <div class="row card-row">
        <div class="col-sm-12 text-center">
        <span style="color: #99ff99; font-size:3rem">✔</span> no timers - all fine
        </div>
    </div>
<?php endif; ?>