<?php if (!empty($struct_list)): ?>
    <?php foreach ($struct_list as $key => $struct): ?>
    <div class="row card-row">
        <div class="col-md-2 text-right">
            <img src="https://images.evetech.net/types/<?=$struct['at_typeId'];?>/render?size=32" alt="Structure type image" title="<?=$this->escapeHtml($struct['it_typename']);?>">
        </div>
        <div class="col-md-6">
            <span class="warnstate" style="margin-bottom:15px;"><?=$this->vpViewTool()->getHumanReadableStructureState($struct['at_structureState']);?></span><br/>
            <?=$this->escapeHtml($struct['at_structureName']);?></span>
            (<?=$this->escapeHtml($struct['own_corpticker']);?>)<br/>
            <span class="secondarytext"><?=($struct['celest_name'] ? $struct['celest_name'] : $struct['map_name'])?></span>
        </div>
        <div class="col-md-4 text-center">
            <?=$this->vpViewTool()->dateUntil('', $struct['at_stateTimerEnd'], 0, 'badge  badge-warning', 'badge badge-normal');?><br/>
            <span class="tertiary"><?=$this->vpViewTool()->formatDateTime($struct['at_stateTimerEnd']);?></span>
        </div>
    </div>
    <?php endforeach;?>
<?php else: ?>
    <div class="row card-row">
        <div class="col-md-12 text-center">
        <span style="color: #99ff99; font-size:3rem">✔</span> no timers - all fine
        </div>
    </div>
<?php endif; ?>