<?php
$this->headTitle("AUTH-Problem");
if(is_array($msg)) {
	$msgarr = '';
	foreach($msg as $singlemsg) {
		$msgarr .= $singlemsg . '</br>';
	}
	$msg = $msgarr;
}


?>

<h1>Authorization Problem</h1>

<div class="alert alert-warning"><?= $msg; ?></div>

<div>Some authorization problems happen while EVE-Online downtime or if some EVO-Online services are not available.<br />
	You may have a look at <a href="http://eve-offline.net/" target="_blank" rel="noopener noreferrer">EVE-Online Status Monitor</a></div>
