<?php
$this->headTitle('ledger');

$this->mainMenu()->setActiveItemId('ledger');

$this->headLink()
	->prependStylesheet($this->basePath('external/highcharts/dark-unica_21-05-23.css'));
$this->headScript()
	->prependFile($this->basePath('external/highcharts/highcharts_9-1-0.js'));


$this->inlineScript()
	->prependFile($this->basePath('js/highchart_ledgerperday.js'));

//echo '<pre>';
//ini_set('xdebug.var_display_max_depth', 3); var_dump($this->currentRoute()->getRoute());
//ini_set('xdebug.var_display_max_depth', 3); var_dump($this->url());
//ini_set('xdebug.var_display_max_depth', 3); var_dump($filters);
//ini_set('xdebug.var_display_max_depth', 3); var_dump($message);
// ini_set('xdebug.var_display_max_depth', 3); var_dump($ledger);
//echo '</pre>';
?>

<?=$this->flashMessenger()->render('error', ['alert', 'alert-warning']);?>
<?=$this->flashMessenger()->render('success', ['alert', 'alert-success']);?>
<?=$this->flashMessenger()->render('info', ['alert', 'alert-info']);?>


<style>
	.highcharts-plot-band {
		fill: rgb(50, 128, 188);
		fill-opacity: 0.1;
	}
</style>

<div class="row">
	<div class="col-md-12 col-sm-12">
		<div class="row">
			<div id="highchartdiv"></div>
		</div>
		<div class="row">
<!-- table start -->
				<table id="ledgertable" class="table table-hover table-striped table-responsive"  aria-describedby="table of ledger">
					<thead>
						<tr>
							<th rowspan="2" data-priority="1" scope="col">Structure Name</th>
							<th rowspan="2" data-priority="2" scope="col">Location</th>
							<th colspan="2" scope="col">refined Value (Mio ISK)</th>
							<th colspan="2" scope="col">Pieces (thousands)</th>
							<th rowspan="2" scope="col">&nbsp;</th>
						</tr>
						<tr>
							<th scope="col">5 Weeks</th>
							<th scope="col">total</th>
							<th scope="col">5 Weeks</th>
							<th scope="col">total</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($ledger as $key => $station): ?>
						<?php // var_export($moon); ?>
						<tr id="tblrow<?=$station['structure_id'];?>">
							<td><?=$station['structure_name'];?></td>
							<td><?=$station['celestial'];?></td>
							<td data-order="<?=$station['cp5w'];?>"><?=number_format($station['cp5w'] / 1000000, 0, ',', '.');?></td>
							<td data-order="<?=$station['cpf'];?>"><?=number_format($station['cpf'] / 1000000, 0, ',', '.');?></td>
							<td data-order="<?=$station['gq5w'];?>"><?=number_format($station['gq5w'] / 1000, 0, ',', '.');?></td>
							<td data-order="<?=$station['gqf'];?>"><?=number_format($station['gqf'] / 1000, 0, ',', '.');?></td>
							<td>
								<?php if($station['celestial']): ?>
								<button type="button" class="btn btn-default btn-xs" onclick="openChildRow(this, <?=$station['structure_id'];?>, '/ledger/chartJson?s='+<?=$station['structure_id'];?>, '<?=addslashes($station['structure_name']);?>');" id="tblrow<?=$station['structure_id'];?>">
									<span class="glyphicon glyphicon-stats"></span> graph</button>
								<?php else: ?>
									&nbsp;
								<?php endif; ?>
							</td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
<!-- table end -->
		</div>
	</div>
</div>
