<?php
$this->headTitle('ledger');

$this->mainMenu()->setActiveItemId('ledger');

$current_route = $this->currentRoute()->getRoute();

//echo '<pre>';
//ini_set('xdebug.var_display_max_depth', 3); var_dump($this->currentRoute()->getRoute());
//ini_set('xdebug.var_display_max_depth', 3); var_dump($this->url());
//ini_set('xdebug.var_display_max_depth', 3); var_dump($filters);
//ini_set('xdebug.var_display_max_depth', 3); var_dump($message);
// ini_set('xdebug.var_display_max_depth', 3); var_dump($ledger);
//echo '</pre>';

if (empty($filters['info_system']['constellation'])) {
    $location_string = $filters['info_system']['itemname'] . ' (Constellation in ' . $filters['info_system']['region'] . ')';
} else {
    $location_string = $filters['info_system']['itemname'] . ' (' . $filters['info_system']['region'] . ')';
}
?>

<?=$this->flashMessenger()->render('error', ['alert', 'alert-warning']);?>
<?=$this->flashMessenger()->render('success', ['alert', 'alert-success']);?>
<?=$this->flashMessenger()->render('info', ['alert', 'alert-info']);?>


<script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <link rel="stylesheet" href="https://code.highcharts.com/css/themes/dark-unica.css">
    <style>
        .highcharts-plot-band {
            fill: rgb(0, 78, 138);
            fill-opacity: 0.05;
        }
    </style>
    <script src="/js/highchart_ledgerperday.js"></script>


<div class="row">
	<div class="col-md-12 col-sm-12">

		<div class="row">
			<div id="highchartdiv"></div>
		</div>
		<div class="row">
<!-- table start -->
				<table id="ledgertable" class="table table-hover table-striped table-responsive"  aria-describedby="table of ledger">
					<thead>
						<tr>
							<th rowspan="2" data-priority="1" scope="col">Structure Name</th>
							<th rowspan="2" data-priority="2" scope="col">Location</th>
							<th colspan="2" scope="col">refined Value (Mio ISK)</th>
							<th colspan="2" scope="col">Pieces (thousands)</th>
							<th rowspan="2" scope="col">&nbsp;</th>
						</tr>
						<tr>
							<th scope="col">5 Weeks</th>
							<th scope="col">total</th>
							<th scope="col">5 Weeks</th>
							<th scope="col">total</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($ledger as $key => $station): ?>
						<?php // var_export($moon); ?>
						<tr id="tblrow<?=$station['structure_id'];?>">
							<td><?=$station['structure_name'];?></td>
							<td><?=$station['celestial'];?></td>
							<td data-order="<?=$station['cp5w'];?>"><?=number_format($station['cp5w'] / 1000000, 0, ',', '.');?></td>
							<td data-order="<?=$station['cpf'];?>"><?=round($station['cpf'] / 1000000, 0);?></td>
							<td data-order="<?=$station['gq5w'];?>"><?=round($station['gq5w'] / 1000, 0);?></td>
							<td data-order="<?=$station['gqf'];?>"><?=round($station['gqf'] / 1000, 0);?></td>
							<td>
								<?php if($station['celestial']): ?>
								<button type="button" class="btn btn-default btn-xs" onclick="openChildRow(this, <?=$station['structure_id'];?>, 'http://annotare.ddns.net/ledger/chartJson?s='+<?=$station['structure_id'];?>, '<?=$station['structure_name'];?>');" id="tblrow<?=$station['structure_id'];?>">
									<span class="glyphicon glyphicon-stats"></span> graph</button>
								<?php else: ?>
									&nbsp;
								<?php endif; ?>
							</td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
<!-- table end -->
		</div>
	</div>
</div>


<!-- Help Modal -->
<div class="modal fade" id="helpModal" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<ul class="nav nav-tabs" id="tabContent">
					<li class="active"><a href="#help_scan" data-toggle="tab">Probe Scanner</a></li>
					<li><a href="#help_dscan" data-toggle="tab">Directional Scanner</a></li>
			</ul>
			</div>
			<div class="tab-content">
				<div class="tab-pane active modal-body" id="help_scan">
					<div class="row">
						<div class="col-md-6">
							<img src="img/eve_scan_window.jpg" alt=""/>
						</div>
						<div class="col-md-6">
							<p>Open your &laquo;Probe Scanner&raquo; window. Please take care your view is <strong>not filtered</strong>.						</p>
							<p>Click inside the Probe Scanne window, select all entries (CTRL-A) and copy them to the clipboard (CTRL-C).</p>
							<p>Now navigate to <span class="skylizer">Syklizer - (D)Scan</span> and paste the result into the big area to the right.</p>
							<p>Then press the button &laquo;submit your scan&raquo; below the area and hold a sec. The table to the left will get updated soon and show your
								scan results.</p>
							<p><strong>Please always copy all entries to ensure the best possible result!</strong></p>
						</div>
					</div>
				</div>
				<div class="tab-pane modal-body" id="help_dscan">
					<div class="row">
						<div class="col-md-6">
							<img src="img/eve_dscan_window.png" alt=""/>
						</div>
						<div class="col-md-6">
							<p>Open your &laquo;Directional Scanner&raquo; window. Please take care your view is <strong>not filtered</strong> and you had set the Range and Angle sliders to their max value.</p>
							<p>Click inside the Probe Scanne window, select all entries (CTRL-A) and copy them to the clipboard (CTRL-C).</p>
							<p>Now navigate to <span class="skylizer">Syklizer - (D)Scan</span> and paste the result into the big area to the right.</p>
							<p>Then press the button &laquo;submit your scan&raquo; below the area and hold a sec. The table to the left will get updated soon and show your
								scan results.</p>
							<p class="skylizer">Please always copy all entries and disable all filters to ensure the best possible result!</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Nope Modal -->
<div class="modal fade" id="nopeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Nope?!</h4>
			</div>
			<div class="modal-body">
				Sorry folks, this function is not supported yet.
			</div>
		</div>
	</div>
</div>