<?php
$this->headTitle('Edit User');

$this->mainMenu()->setActiveItemId('admin');

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<h1>Edit User <?= $this->escapeHtml($user->getEveUsername()); ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
		<input type="hidden" name="id" value="<?=$user->getId(); ?>">
        
        <div class="form-group">
			<label for="userid">UserId</label>
			<input type="text" disabled value="<?= $this->escapeHtml($user->getEveUserid()); ?>" name="userid"  class="form-control">
        </div>
        
        <div class="form-group">
			<label for="username">UserName</label>
			<input type="text" disabled value="<?= $this->escapeHtml($user->getEveUsername()); ?>" name="username"  class="form-control">
        </div>
        
        <div class="form-group">
			<label for="corporationname">Corporation</label>
			<input type="text" disabled value="<?= $this->escapeHtml($user->getEveCorpid()->getCorporationName()); ?>" name="corporationname"  class="form-control">
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('roles')); ?>
            <?= $this->formElement($form->get('roles')); ?>
            <?= $this->formElementErrors($form->get('roles')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

