<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('admin');
?>

<div class="page-header">
	<h1 id="navbar">Manage Users</h1>
</div>

<table class="table table-striped table-hover" id="admintable" aria-describedby="User view">
	<th scope="col"ead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">EVE Name</th>
			<th scope="col">Corporation</th>
			<th scope="col">Role(s)</th>
			<th scope="col">Date Created</th>
			<th scope="col">Status</th>
			<th scope="col">Actions</th>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($users as $user): ?>
			<tr>
				<td><?=$this->escapeHtml($user->getId());?></td>
				<td>
					<img src="https://imageserver.eveonline.com/Character/<?=$user->getEveUserid();?>_32.jpg" alt="user face">&nbsp;
					<?=$this->escapeHtml($user->getEveUsername());?>
				</td>
				<td>
				<?php if ($user->getEveCorpid()): ?>
					<img src="https://imageserver.eveonline.com/Corporation/<?=$user->getEveCorpid()->getCorporationId();?>_32.png" alt="corp logo">&nbsp;
					<?=$this->escapeHtml($user->getEveCorpid()->getCorporationName());?>
				<?php endif;?>
				</td>
				<td>
					<?=$this->escapeHtml($user->getRolesAsString());?></a>
				</td>
				<td><?=$this->escapeHtml($user->getDateCreated()->format('d.m.Y H:i:s'));?></td>
	<td><?=$this->escapeHtml($user->getStatusAsString());?></td>
	<td>
		<a class="btn btn-info btn-sm" href="<?=$this->url('users', ['action' => 'edit', 'id' => $user->getId()]); ?>">
			<span class="glyphicon glyphicon-pencil" ></span> Edit
		</a>
	</td>
	</tr>
<?php endforeach;?>
</tbody>
</table>

