<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('admin');
?>

<div class="page-header">
	<h1 id="navbar">Manage Users</h1>
</div>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>EVE Name</th>
			<th>Corporation</th>
			<th>Role(s)</th>        
			<th>Date Created</th>
			<th>Status</th>        
			<th>Actions</th>        
		</tr>
	</thead>

	<tbody>
		<?php foreach ($users as $user): ?>
			<tr>
				<td><?= $this->escapeHtml($user->getId()); ?></td>
				<td>
					<img src="http://imageserver.eveonline.com/Character/<?= $user->getEveUserid(); ?>_32.jpg">&nbsp;
					<?= $this->escapeHtml($user->getEveUsername()); ?>
				</td>
				<td>
					<img src="http://imageserver.eveonline.com/Corporation/<?= $user->getEveCorpid()->getCorporationId(); ?>_32.png">&nbsp;
					<?= $this->escapeHtml($user->getEveCorpid()->getCorporationName()); ?>
				</td>
				<td>
					<?= $this->escapeHtml($user->getRolesAsString()); ?></a> 
				</td>
				<td><nobr><?= $this->escapeHtml($user->getDateCreated()->format('d.m.Y H:i:s')); ?></nobr></td>        
	<td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
	<td>
		<a class="btn btn-info btn-sm" href="<?= $this->url('users', ['action' => 'edit', 'id' => $user->getId()]);
				?>">
			<span class="glyphicon glyphicon-pencil" ></span> Edit
		</a>
	</td>    
	</tr>
<?php endforeach; ?>   
</tbody>
</table>

