<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('admin');
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User <?= $this->escapeHtml($user->getEveUsername()); ?>&nbsp;
<img src="https://imageserver.eveonline.com/Corporation/<?= $user->getEveCorpid()->getCorporationId(); ?>_64.png" alt="corp logo">&nbsp;
<img src="https://imageserver.eveonline.com/Character/<?= $user->getEveUserid(); ?>_64.jpg" alt="users face">
</h1>

<p>
    <a class="btn btn-default" href="<?= $this->url('users', 
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()); ?></td>
            </tr>
            <tr>
                <th>Eve-ID:</th>
                <td><?= $this->escapeHtml($user->getEveUserid()); ?></td>
            </tr>
            <tr>
                <th>Eve Name:</th>
                <td><?= $this->escapeHtml($user->getEveUsername()); ?></td>
            </tr>
            <tr>
                <th>Eve Corporation:</th>
                <td><?= $this->escapeHtml($user->getEveCorpid()->getCorporationName()); ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()->format('d.m.Y H:i:s')) ?></td>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></td>
            </tr>
            <tr>
                <th>Roles:</th>
                <td><?= $this->escapeHtml($user->getRolesAsString()) ?></td>
            </tr>
        </table>
    </div>
</div>