<?php
$this->headTitle('Roles');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Roles' => $this->url('roles'),
]);
?>

<h1>Manage Roles</h1>

<?=$this->flashMessenger()->render('error', ['alert', 'alert-warning']);?>
<?=$this->flashMessenger()->render('success', ['alert', 'alert-success']);?>
<?=$this->flashMessenger()->render('info', ['alert', 'alert-info']);?>

<p>
<a class="btn btn-default" href="
    <?=$this->url('roles', ['action' => 'add']);?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Role
</a>
</p>

<table class="table table-striped" aria-describedby="Roles view">

   <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Date Created</th>
        <th scope="col">Actions</th>
    </tr>

    <?php foreach ($roles as $role): ?>

    <tr>
        <td><?=$this->escapeHtml($role->getId());?></td>
        <td>
            <a href="<?=$this->url('roles', ['action' => 'view', 'id' => $role->getId()]);?>">
                <?=$this->escapeHtml($role->getName());?></a>
        </td>
        <td><?=$this->escapeHtml($role->getDescription());?></a>
        </td>
        <td><?=$this->escapeHtml($role->getDateCreated());?></td>
        <td>
            <a class="btn btn-info" href="<?=$this->url('roles', ['action' => 'edit', 'id' => $role->getId()]);?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit</a>
            <a class="btn btn-danger" href="<?=$this->url('roles', ['action' => 'delete', 'id' => $role->getId()]);?>">
                <span class="glyphicon glyphicon-remove"></span> Delete</a>
        </td>
    </tr>

    <?php endforeach;?>

</table>




