<?php
$this->headTitle('View Permission');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Permissions'=>$this->url('permissions'),
            'View Permission'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
            ]);
?>


<h1>View Permission</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered" aria-describedby="Permissions view">
             <tr>
                <th aria-describedby="Settings overview">ID:</th>
                <td scope="col"><?= $this->escapeHtml($permission->getId()) ?></th>
            </tr>
            <tr>
                <th aria-describedby="Settings overview">Name:</th>
                <td scope="col"><?= $this->escapeHtml($permission->getName()) ?></th>
            </tr>
            <tr>
                <th aria-describedby="Settings overview">Description:</th>
                <td scope="col"><?= $this->escapeHtml($permission->getDescription()) ?></th>
            </tr>
            <tr>
                <th aria-describedby="Settings overview">Date Created:</th>
                <td scope="col"><?= $this->escapeHtml($permission->getDateCreated()->format('d.m.Y H:i:s')) ?></th>
            </tr>
        </table>
    </div>
</div>