<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
	'Home' => $this->url('home'),
	'About' => $this->url('about'),
]);
?>
<div class="page-header">
	<h1 id="navbar">About</h1>
</div>

<p>
	skŸlizer is a tool for Eve Online to handle any kind of scans and to gather as much as possible data from the scan.<br>
    At the moment scanning moons and scanning anomalies are supported.</p>
<p>
	The source code of skŸlizer is available at <a href="https://github.com/chrRtg/eve-skylizer" target="_blank">Github: chrRtg/eve-skylizer</a>.
	On Github you'll also find a screenshot, a list of features, a install guide and much more.
</p>

<p>
	If you found a mistake or a bug please get in touch via:
	<ul>
		<li>Github for <a href="https://github.com/chrRtg/eve-skylizer/issues" target="_blank">issues</a> or <a href="https://github.com/chrRtg/eve-skylizer/pulls" target="_blank">suggestions</a> </li>
		<li>the Eve online Forum thread about skŸlizer</li>
		<li>Eve ingame mail to 'Rtg Quack'</li>
	</ul>
</p>

<p>
	If you want to know more about Eve online please visit the official website <a href="https://www.eveonline.com/" target="_blank">www.eveonline.com</a>.
</p>
