<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
		'Home' => $this->url('home'),
		'About' => $this->url('about'),
]);
?>
<div class="page-header">
	<h1 id="navbar">About</h1>
</div>


<p>
    This tool is brought to by by Rtg Quack.
</p>

<p>
    Sylizer is a tool to handle any kind of scans from within Eve Online. If you want to know more about Eve online please visit the official website <a href="https://www.eveonline.com/" target="_blank">www.eveonline.com</a>.
</p>
