<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<div class="jumbotron">
  <h1>Welcome</h1>
<p>
    skŸlizer is a tool for Eve Online to handle any kind of scans. At the moment only survey scans of moon are supported.
</p>

<p>
	<a href="<?= $this->url('auth', ['action' => 'index']); ?>"><img src="<?= $this->basePath('img/'); ?>EVE_SSO_Login_Buttons_Large_White.png"></a>
</p>
</div>



