<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<div class="jumbotron">
  <h1>Welcome</h1>
<p>
  skŸlizer is a tool for Eve Online to handle any kind of scans and to gather as much as possible data from the scan.<br>
  At the moment scanning moons, anomalies and citatadels are supported.</p>
</p>

<p>
	<a href="<?= $this->url('auth', ['action' => 'index']); ?>"><img src="<?= $this->basePath('img/'); ?>EVE_SSO_Login_Buttons_Large_White.png" alt="EVE SSO Login Button"></a>
</p>
<p style="padding-top: 30px;">
  <h4>Alternative Login:</h4>
	<a href="<?= $this->url('auth', ['action' => 'index'], array('query' => array('logintype' => 'mining'))); ?>" title="EVE SSO Login for CorpDirector"  class="btn btn-default btn-s">Corp Director Login</a>
</p>

</div>



