<?php
$this->headTitle('Settings');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
		'Home' => $this->url('home'),
		'Settings' => $this->url('application', ['action' => 'settings']),
]);
?>

<div class="page-header">
	<h1 id="navbar">Settings</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-hover" aria-describedby="Settings overview">
			<thead>
				<tr>
					<th scope="col">ID:</th>
					<th scope="col">E-mail:</th>
					<th scope="col">Full Name:</th>
					<th scope="col">Date Created:</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><?= $this->escapeHtml($user->getId()) ?></td>
					<td><?= $this->escapeHtml($user->getEmail()) ?></td>
					<td><?= $this->escapeHtml($user->getFullName()) ?></td>
					<td><?= $this->escapeHtml($user->getDateCreated()->format('d.m.Y H:i:s')) ?></td>
				</tr>
			</tbody>
        </table>
    </div>
</div>